In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [2]:
data= pd.read_csv(r'C:\Users\ABHI DEVARADDI\OneDrive\Dokumen\aicwe\Churn_Analysis\Churn_Modelling (1).csv')

In [3]:
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [4]:
data.shape

(10000, 14)

In [5]:
data.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='str')

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  str
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  str
 5   Gender           10000 non-null  str
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), str(3)
memory usage: 1.1 MB

In [7]:
data.drop(['RowNumber','CustomerId','Surname'],axis=1,inplace=True)

In [8]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [9]:
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [10]:
#label encoding
label_encoder_gender= LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [11]:
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder_geography= OneHotEncoder()
geo_encoder= one_hot_encoder_geography.fit_transform(data[['Geography']]).toarray()
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [12]:
one_hot_encoder_geography.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [13]:
geo_df= pd.DataFrame(geo_encoder,columns=one_hot_encoder_geography.get_feature_names_out(['Geography']))

In [14]:
geo_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [15]:
data= pd.concat([data.drop('Geography',axis=1),geo_df],axis=1)

In [16]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [17]:
#save one hot encoding and label encoding
with open('label_encoder_gender,pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

In [18]:
with open('one_hot_encoder_geography.pkl','wb') as file:
    pickle.dump(one_hot_encoder_geography,file)

In [19]:
x=data.drop('Exited',axis=1)
y=data['Exited']

In [22]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=42)

In [23]:
from sklearn.preprocessing import StandardScaler

In [25]:
ss = StandardScaler()
x_train_scaled = ss.fit_transform(x_train)
x_test_scaled = ss.transform(x_test)

ANN IMPLEMENTATION

In [34]:
! pip install tensorflow

Collecting tensorflow
  Using cached tensorflow-2.21.0-cp313-cp313-win_amd64.whl.metadata (4.5 kB)
Requirement already satisfied: absl-py>=1.0.0 in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: astunparse>=1.6.0 in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in C:\Users\ABHI DEVARADDI\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (26.2)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow) (7.35.1)
Requirement already satisfied: requests<3,>=2.21.0 in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow) (2.34.2)
Requirement already satisfied: setuptools in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow) (84.0.0)
Requirement already satisfied: six>=1.12.0 in C:\Users\ABHI DEVARADDI\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in C:\Users\ABHI DEVARADDI\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow) (2.3.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow) (1.83.0)
Requirement already satisfied: keras>=3.12.0 in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow) (3.15.1)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow) (2.5.1)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.5.0)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.7.22)
Requirement already satisfied: wheel<1.0,>=0.23.0 in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.48.0)
Requirement already satisfied: rich in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\ABHI DEVARADDI\AppData\Roaming\Python\Python313\site-packages (from rich->keras>=3.12.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Using cached tensorflow-2.21.0-cp313-cp313-win_amd64.whl (351.2 MB)
Installing collected packages: tensorflow
Successfully installed tensorflow-2.21.0

Collecting tensorflow
  Using cached tensorflow-2.21.0-cp313-cp313-win_amd64.whl.metadata (4.5 kB)
Collecting absl-py>=1.0.0 (from tensorflow)
  Using cached absl_py-2.5.0-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow)
  Using cached flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Using cached gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in C:\Users\ABHI DEVARADDI\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (26.2)
Collecting protobuf<8.0.0,>=6.31.1 (from tensorflow)
  Using cached protobuf-7.35.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Collecting requests<3,>=2.21.0 (from tensorflow)
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting setuptools (from tensorflow)
  Using cached setuptools-84.0.0-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: six>=1.12.0 in C:\Users\ABHI DEVARADDI\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Using cached termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in C:\Users\ABHI DEVARADDI\AppData\Roaming\Python\Python313\site-packages (from tensorflow) (4.16.0)
Collecting wrapt>=1.11.0 (from tensorflow)
  Using cached wrapt-2.3.0-cp313-cp313-win_amd64.whl.metadata (7.6 kB)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow)
  Using cached grpcio-1.83.0-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
Collecting keras>=3.12.0 (from tensorflow)
  Using cached keras-3.15.1-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tensorflow) (2.5.1)
Collecting h5py<3.15.0,>=3.11.0 (from tensorflow)
  Using cached h5py-3.14.0-cp313-cp313-win_amd64.whl.metadata (2.7 kB)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Using cached ml_dtypes-0.6.0-cp313-cp313-win_amd64.whl.metadata (8.8 kB)
Collecting charset_normalizer<4,>=2 (from requests<3,>=2.21.0->tensorflow)
  Using cached charset_normalizer-3.5.0-cp313-cp313-win_amd64.whl.metadata (44 kB)
Collecting idna<4,>=2.5 (from requests<3,>=2.21.0->tensorflow)
  Using cached idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting urllib3<3,>=1.26 (from requests<3,>=2.21.0->tensorflow)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests<3,>=2.21.0->tensorflow)
  Using cached certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Collecting wheel<1.0,>=0.23.0 (from astunparse>=1.6.0->tensorflow)
  Using cached wheel-0.48.0-py3-none-any.whl.metadata (2.3 kB)
Collecting rich (from keras>=3.12.0->tensorflow)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting namex (from keras>=3.12.0->tensorflow)
  Using cached namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.12.0->tensorflow)
  Using cached optree-0.19.1-cp313-cp313-win_amd64.whl.metadata (32 kB)
Collecting markdown-it-py>=2.2.0 (from rich->keras>=3.12.0->tensorflow)
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\ABHI DEVARADDI\AppData\Roaming\Python\Python313\site-packages (from rich->keras>=3.12.0->tensorflow) (2.20.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading tensorflow-2.21.0-cp313-cp313-win_amd64.whl (351.2 MB)
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.5/351.2 MB 154.7 kB/s eta 0:37:47
   ---------------------------------------- 0.5/351.2 MB 154.7 kB/s eta 0:37:47
   ---------------------------------------- 0.5/351.2 MB 154.7 kB/s eta 0:37:47
   ---------------------------------------- 0.5/351.2 MB 154.7 kB/s eta 0:37:47
   ---------------------------------------- 0.5/351.2 MB 154.7 kB/s eta 0:37:47
   ---------------------------------------- 0.5/351.2 MB 154.7 kB/s eta 0:37:47
   ---------------------------------------- 0.8/351.2 MB 185.3 kB/s eta 0:31:32
   ---------------------------------------- 0.8/351.2 MB 185.3 kB/s eta 0:31:32
   ---------------------------------------- 0.8/351.2 MB 185.3 kB/s eta 0:31:32
   ---------------------------------------- 0.8/351.2 MB 185.3 kB/s eta 0:31:32
   ---------------------------------------- 0.8/351.2 MB 185.3 kB/s eta 0:31:32
   ---------------------------------------- 0.8/351.2 MB 185.3 kB/s eta 0:31:32
   ---------------------------------------- 0.8/351.2 MB 185.3 kB/s eta 0:31:32
   ---------------------------------------- 0.8/351.2 MB 185.3 kB/s eta 0:31:32
   ---------------------------------------- 0.8/351.2 MB 185.3 kB/s eta 0:31:32
   ---------------------------------------- 0.8/351.2 MB 185.3 kB/s eta 0:31:32
   ---------------------------------------- 0.8/351.2 MB 185.3 kB/s eta 0:31:32
   ---------------------------------------- 0.8/351.2 MB 185.3 kB/s eta 0:31:32
   ---------------------------------------- 0.8/351.2 MB 185.3 kB/s eta 0:31:32
   ---------------------------------------- 0.8/351.2 MB 185.3 kB/s eta 0:31:32
   ---------------------------------------- 0.8/351.2 MB 185.3 kB/s eta 0:31:32
   ---------------------------------------- 0.8/351.2 MB 185.3 kB/s eta 0:31:32
   ---------------------------------------- 0.8/351.2 MB 185.3 kB/s eta 0:31:32
   ---------------------------------------- 0.8/351.2 MB 185.3 kB/s eta 0:31:32
   ---------------------------------------- 0.8/351.2 MB 185.3 kB/s eta 0:31:32
   ---------------------------------------- 0.8/351.2 MB 185.3 kB/s eta 0:31:32
   ---------------------------------------- 0.8/351.2 MB 185.3 kB/s eta 0:31:32
   ---------------------------------------- 0.8/351.2 MB 185.3 kB/s eta 0:31:32
   ---------------------------------------- 0.8/351.2 MB 185.3 kB/s eta 0:31:32
   ---------------------------------------- 1.0/351.2 MB 102.2 kB/s eta 0:57:08
   ---------------------------------------- 1.0/351.2 MB 102.2 kB/s eta 0:57:08
   ---------------------------------------- 1.0/351.2 MB 102.2 kB/s eta 0:57:08
   ---------------------------------------- 1.0/351.2 MB 102.2 kB/s eta 0:57:08
   ---------------------------------------- 1.0/351.2 MB 102.2 kB/s eta 0:57:08
   ---------------------------------------- 1.0/351.2 MB 102.2 kB/s eta 0:57:08
   ---------------------------------------- 1.0/351.2 MB 102.2 kB/s eta 0:57:08
   ---------------------------------------- 1.0/351.2 MB 102.2 kB/s eta 0:57:08
   ---------------------------------------- 1.3/351.2 MB 111.0 kB/s eta 0:52:33
   ---------------------------------------- 1.3/351.2 MB 111.0 kB/s eta 0:52:33
   ---------------------------------------- 1.3/351.2 MB 111.0 kB/s eta 0:52:33
   ---------------------------------------- 1.3/351.2 MB 111.0 kB/s eta 0:52:33
   ---------------------------------------- 1.3/351.2 MB 111.0 kB/s eta 0:52:33
   ---------------------------------------- 1.3/351.2 MB 111.0 kB/s eta 0:52:33
   ---------------------------------------- 1.3/351.2 MB 111.0 kB/s eta 0:52:33
   ---------------------------------------- 1.6/351.2 MB 120.3 kB/s eta 0:48:28
   ---------------------------------------- 1.6/351.2 MB 120.3 kB/s eta 0:48:28
   ---------------------------------------- 1.6/351.2 MB 120.3 kB/s eta 0:48:28
   ---------------------------------------- 1.6/351.2 MB 120.3 kB/s eta 0:48:28
   ---------------------------------------- 1.6/351.2 MB 120.3 kB/s eta 0:48:28
   ---------------------------------------- 1.8/351.2 MB 130.9 kB/s eta 0:44:30
   ---------------------------------------- 1.8/351.2 MB 130.9 kB/s eta 0:44:30
   ---------------------------------------- 1.8/351.2 MB 130.9 kB/s eta 0:44:30
   ---------------------------------------- 1.8/351.2 MB 130.9 kB/s eta 0:44:30
   ---------------------------------------- 2.1/351.2 MB 141.6 kB/s eta 0:41:06
   ---------------------------------------- 2.1/351.2 MB 141.6 kB/s eta 0:41:06
   ---------------------------------------- 2.1/351.2 MB 141.6 kB/s eta 0:41:06
   ---------------------------------------- 2.4/351.2 MB 155.0 kB/s eta 0:37:31
   ---------------------------------------- 2.6/351.2 MB 171.7 kB/s eta 0:33:50
   ---------------------------------------- 2.9/351.2 MB 188.6 kB/s eta 0:30:47
   ---------------------------------------- 3.1/351.2 MB 204.9 kB/s eta 0:28:19
   ---------------------------------------- 3.7/351.2 MB 237.1 kB/s eta 0:24:27
   ---------------------------------------- 4.2/351.2 MB 269.8 kB/s eta 0:21:27
   ---------------------------------------- 4.2/351.2 MB 269.8 kB/s eta 0:21:27
    --------------------------------------- 4.5/351.2 MB 278.8 kB/s eta 0:20:44
    --------------------------------------- 4.5/351.2 MB 278.8 kB/s eta 0:20:44
    --------------------------------------- 4.7/351.2 MB 290.2 kB/s eta 0:19:54
    --------------------------------------- 4.7/351.2 MB 290.2 kB/s eta 0:19:54
    --------------------------------------- 4.7/351.2 MB 290.2 kB/s eta 0:19:54
    --------------------------------------- 5.0/351.2 MB 293.7 kB/s eta 0:19:40
    --------------------------------------- 5.5/351.2 MB 320.3 kB/s eta 0:18:00
    --------------------------------------- 5.8/351.2 MB 334.0 kB/s eta 0:17:15
    --------------------------------------- 6.0/351.2 MB 346.3 kB/s eta 0:16:37
    --------------------------------------- 6.8/351.2 MB 386.7 kB/s eta 0:14:51
    --------------------------------------- 8.1/351.2 MB 456.5 kB/s eta 0:12:32
   - -------------------------------------- 9.2/351.2 MB 511.3 kB/s eta 0:11:09
   - ------------------------------------- 10.2/351.2 MB 564.5 kB/s eta 0:10:05
   - ------------------------------------- 11.0/351.2 MB 603.1 kB/s eta 0:09:25
   - ------------------------------------- 12.1/351.2 MB 653.9 kB/s eta 0:08:39
   - ------------------------------------- 13.1/351.2 MB 702.2 kB/s eta 0:08:02
   - ------------------------------------- 13.9/351.2 MB 738.0 kB/s eta 0:07:38
   - ------------------------------------- 14.7/351.2 MB 771.5 kB/s eta 0:07:17
   - ------------------------------------- 15.5/351.2 MB 805.7 kB/s eta 0:06:57
   - ------------------------------------- 16.3/351.2 MB 836.1 kB/s eta 0:06:41
   - ------------------------------------- 17.0/351.2 MB 867.6 kB/s eta 0:06:26
   - ------------------------------------- 17.6/351.2 MB 887.5 kB/s eta 0:06:16
   -- ------------------------------------ 18.4/351.2 MB 917.1 kB/s eta 0:06:03
   -- ------------------------------------ 18.9/351.2 MB 933.9 kB/s eta 0:05:56
   -- ------------------------------------ 19.7/351.2 MB 962.7 kB/s eta 0:05:45
   -- ------------------------------------ 20.4/351.2 MB 992.1 kB/s eta 0:05:34
   -- ------------------------------------- 21.2/351.2 MB 1.0 MB/s eta 0:05:25
   -- ------------------------------------- 21.8/351.2 MB 1.0 MB/s eta 0:05:18
   -- ------------------------------------- 22.3/351.2 MB 1.0 MB/s eta 0:05:15
   -- ------------------------------------- 23.1/351.2 MB 1.1 MB/s eta 0:05:06
   -- ------------------------------------- 23.6/351.2 MB 1.1 MB/s eta 0:05:01
   -- ------------------------------------- 24.4/351.2 MB 1.1 MB/s eta 0:04:54
   -- ------------------------------------- 25.2/351.2 MB 1.1 MB/s eta 0:04:46
   -- ------------------------------------- 26.0/351.2 MB 1.2 MB/s eta 0:04:40
   --- ------------------------------------ 26.7/351.2 MB 1.2 MB/s eta 0:04:33
   --- ------------------------------------ 27.5/351.2 MB 1.2 MB/s eta 0:04:27
   --- ------------------------------------ 28.0/351.2 MB 1.2 MB/s eta 0:04:24
   --- ------------------------------------ 28.8/351.2 MB 1.2 MB/s eta 0:04:19
   --- ------------------------------------ 29.6/351.2 MB 1.3 MB/s eta 0:04:13
   --- ------------------------------------ 30.4/351.2 MB 1.3 MB/s eta 0:04:09
   --- ------------------------------------ 30.9/351.2 MB 1.3 MB/s eta 0:04:06
   --- ------------------------------------ 31.5/351.2 MB 1.3 MB/s eta 0:04:03
   --- ------------------------------------ 32.2/351.2 MB 1.3 MB/s eta 0:03:59
   --- ------------------------------------ 32.8/351.2 MB 1.3 MB/s eta 0:03:57
   --- ------------------------------------ 33.6/351.2 MB 1.4 MB/s eta 0:03:53
   --- ------------------------------------ 34.3/351.2 MB 1.4 MB/s eta 0:03:49
   ---- ----------------------------------- 35.4/351.2 MB 1.4 MB/s eta 0:03:44
   ---- ----------------------------------- 36.2/351.2 MB 1.4 MB/s eta 0:03:40
   ---- ----------------------------------- 37.0/351.2 MB 1.5 MB/s eta 0:03:36
   ---- ----------------------------------- 37.7/351.2 MB 1.5 MB/s eta 0:03:33
   ---- ----------------------------------- 38.5/351.2 MB 1.5 MB/s eta 0:03:30
   ---- ----------------------------------- 39.6/351.2 MB 1.5 MB/s eta 0:03:26
   ---- ----------------------------------- 40.4/351.2 MB 1.5 MB/s eta 0:03:23
   ---- ----------------------------------- 41.2/351.2 MB 1.6 MB/s eta 0:03:20
   ---- ----------------------------------- 42.2/351.2 MB 1.6 MB/s eta 0:03:16
   ---- ----------------------------------- 43.0/351.2 MB 1.6 MB/s eta 0:03:13
   ---- ----------------------------------- 43.8/351.2 MB 1.6 MB/s eta 0:03:11
   ----- ---------------------------------- 44.8/351.2 MB 1.6 MB/s eta 0:03:07
   ----- ---------------------------------- 45.6/351.2 MB 1.7 MB/s eta 0:03:05
   ----- ---------------------------------- 46.7/351.2 MB 1.7 MB/s eta 0:03:01
   ----- ---------------------------------- 47.4/351.2 MB 1.7 MB/s eta 0:02:59
   ----- ---------------------------------- 48.2/351.2 MB 1.7 MB/s eta 0:02:57
   ----- ---------------------------------- 49.0/351.2 MB 1.7 MB/s eta 0:02:55
   ----- ---------------------------------- 50.1/351.2 MB 1.8 MB/s eta 0:02:52
   ----- ---------------------------------- 50.9/351.2 MB 1.8 MB/s eta 0:02:50
   ----- ---------------------------------- 51.6/351.2 MB 1.8 MB/s eta 0:02:48
   ------ --------------------------------- 52.7/351.2 MB 1.8 MB/s eta 0:02:46
   ------ --------------------------------- 53.5/351.2 MB 1.8 MB/s eta 0:02:44
   ------ --------------------------------- 54.3/351.2 MB 1.8 MB/s eta 0:02:42
   ------ --------------------------------- 55.1/351.2 MB 1.8 MB/s eta 0:02:41
   ------ --------------------------------- 56.1/351.2 MB 1.9 MB/s eta 0:02:38
   ------ --------------------------------- 56.9/351.2 MB 2.0 MB/s eta 0:02:29
   ------ --------------------------------- 57.9/351.2 MB 2.0 MB/s eta 0:02:27
   ------ --------------------------------- 58.7/351.2 MB 2.0 MB/s eta 0:02:25
   ------ --------------------------------- 59.5/351.2 MB 2.0 MB/s eta 0:02:24
   ------ --------------------------------- 60.3/351.2 MB 2.0 MB/s eta 0:02:23
   ------ --------------------------------- 61.3/351.2 MB 2.1 MB/s eta 0:02:21
   ------- -------------------------------- 62.1/351.2 MB 2.1 MB/s eta 0:02:20
   ------- -------------------------------- 62.9/351.2 MB 2.1 MB/s eta 0:02:18
   ------- -------------------------------- 63.7/351.2 MB 2.2 MB/s eta 0:02:13
   ------- -------------------------------- 64.5/351.2 MB 2.2 MB/s eta 0:02:12
   ------- -------------------------------- 65.3/351.2 MB 2.2 MB/s eta 0:02:11
   ------- -------------------------------- 66.3/351.2 MB 2.2 MB/s eta 0:02:09
   ------- -------------------------------- 67.1/351.2 MB 2.2 MB/s eta 0:02:08
   ------- -------------------------------- 67.9/351.2 MB 2.7 MB/s eta 0:01:47
   ------- -------------------------------- 68.2/351.2 MB 2.7 MB/s eta 0:01:47
   ------- -------------------------------- 68.7/351.2 MB 2.7 MB/s eta 0:01:47
   ------- -------------------------------- 69.2/351.2 MB 2.6 MB/s eta 0:01:47
   ------- -------------------------------- 70.0/351.2 MB 2.7 MB/s eta 0:01:46
   -------- ------------------------------- 70.5/351.2 MB 2.7 MB/s eta 0:01:46
   -------- ------------------------------- 70.8/351.2 MB 2.7 MB/s eta 0:01:46
   -------- ------------------------------- 71.3/351.2 MB 2.6 MB/s eta 0:01:47
   -------- ------------------------------- 71.8/351.2 MB 2.6 MB/s eta 0:01:46
   -------- ------------------------------- 72.6/351.2 MB 2.6 MB/s eta 0:01:46
   -------- ------------------------------- 73.1/351.2 MB 2.6 MB/s eta 0:01:45
   -------- ------------------------------- 73.7/351.2 MB 2.7 MB/s eta 0:01:45
   -------- ------------------------------- 74.4/351.2 MB 2.7 MB/s eta 0:01:45
   -------- ------------------------------- 75.0/351.2 MB 2.7 MB/s eta 0:01:45
   -------- ------------------------------- 75.8/351.2 MB 2.7 MB/s eta 0:01:44
   -------- ------------------------------- 76.5/351.2 MB 2.7 MB/s eta 0:01:43
   -------- ------------------------------- 76.8/351.2 MB 2.7 MB/s eta 0:01:43
   -------- ------------------------------- 76.8/351.2 MB 2.7 MB/s eta 0:01:43
   -------- ------------------------------- 76.8/351.2 MB 2.7 MB/s eta 0:01:43
   --------- ------------------------------ 79.7/351.2 MB 2.7 MB/s eta 0:01:41
   --------- ------------------------------ 80.7/351.2 MB 2.7 MB/s eta 0:01:40
   --------- ------------------------------ 81.5/351.2 MB 2.7 MB/s eta 0:01:39
   --------- ------------------------------ 82.6/351.2 MB 2.7 MB/s eta 0:01:39
   --------- ------------------------------ 83.1/351.2 MB 2.7 MB/s eta 0:01:38
   --------- ------------------------------ 83.9/351.2 MB 2.9 MB/s eta 0:01:33
   --------- ------------------------------ 84.4/351.2 MB 2.9 MB/s eta 0:01:32

In [35]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [36]:
x_train.shape

(8000, 12)

In [37]:
#build our ann model
model = Sequential([
    Dense(64, activation='relu', input_shape=(x_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(32, activation='sigmoid'),
])

c:\Users\ABHI DEVARADDI\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [38]:
(x_train.shape[1],)

(12,)

In [39]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         1,056 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,968 (15.50 KB)

 Trainable params: 3,968 (15.50 KB)

 Non-trainable params: 0 (0.00 B)

In [40]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
print(loss)

<LossFunctionWrapper(<function binary_crossentropy at 0x000001F7FBE79BC0>, kwargs={'from_logits': False, 'label_smoothing': 0.0, 'axis': -1})>

In [54]:
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])

In [56]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [ ]:
=EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)